### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Tylian** [Tylian/rdm#1]
I'm going to leave a list of stuff that's on my todo list for this simulator here, so people know what to expect.

## Todo
- [ ] Toggle to disable tooltips
- [ ] Option to change spell speed scaling factor
- [ ] Allow moving of skills, so people can set up their hotbars however they wish
- [ ] Action log (each action as used, what time, effective potency when used, and also all active status effects (including embolden's stage), black/white mana and total potency per second)
- [ ] Clean up the mana gauge
- [ ] Make realtime mode freeze before the GCD rather than after, till future input is known

## Done
- [x] ~~Add the skill queue~~
- [x] ~~Show ability keybinds on the icon itself~~
- [x] ~~Clean up the casting bar (i.e. showing a big skill icon beside the bar, like in game)~~
- [x] ~~Break melee combos after a specific number of seconds~~
- [x] ~~Require action skill to be combo'd during a combo if it can be~~

**Comment by EBorroughs** [comment]
Zwerchhau, enchanted zwerchhau, and redoublement use 100 potency when comboed instead of their proper potencies based on the damage numbers that are displayed, and enchanted redoublement has 470 uncomboed potency instead of 100. Also, based on gameplay and the ability descriptions that were released, it looks like enchanted riposte and enchanted zwerchhau are supposed to have recast times of 1.5s and enchanted redoublement has a recast time of 2.2s.

**Comment by Tylian** [comment]
@EBorroughs
Fixed the issue with combo potency in commit 7c9ac48aae43dd372474ba00994cabb017c845c8, thanks!

As for the recast timers, they are 1.5, 1.5 and 2.2 on the Enchanted versions, both in the description and in the simulation itself.

Also, next time open a new issue so I can reference it in the fix commit, please. Thanks!

**Comment by montijin** [comment]
Is there any way we could have an option to turn off the tooltips in the settings? They kind of obstruct where the buttons are and if you already know what each skill looks like and does it would be nice to have the option to turn it off. Love the tool, thanks.

**Comment by Tylian** [comment]
Yeah sure, I'll add that in my next coding session.
